import type { Categoria, Inspiracao } from '../../../shared/features/inspiracao/inspiracao.types'

// Dados mockados enquanto não há admin dashboard para cadastrar inspirações.
// O service lê daqui no lugar do banco, e o seed (prisma/seed.dados.ts) reaproveita a mesma lista.

export const categorias: Categoria[] = [
  // Segmento
  { slug: 'saas', nome: 'SaaS', grupo: 'segmento' },
  { slug: 'fintech', nome: 'Fintech', grupo: 'segmento' },
  { slug: 'ia', nome: 'IA', nomeCompleto: 'Inteligência artificial', grupo: 'segmento' },
  {
    slug: 'dev-tools',
    nome: 'Dev tools',
    nomeCompleto: 'Ferramentas para desenvolvedores',
    grupo: 'segmento',
  },
  // Estilo
  { slug: 'pb', nome: 'P&B', nomeCompleto: 'Preto e branco', grupo: 'estilo' },
  { slug: 'modo-escuro', nome: 'Modo escuro', grupo: 'estilo' },
  { slug: 'minimalista', nome: 'Minimalista', grupo: 'estilo' },
  { slug: 'moderno', nome: 'Moderno', grupo: 'estilo' },
  { slug: 'gradiente', nome: 'Gradiente', grupo: 'estilo' },
  { slug: 'editorial', nome: 'Editorial', grupo: 'estilo' },
  { slug: 'animado', nome: 'Animado', grupo: 'estilo' },
]

// Na ordem de exibição (equivale ao `criadoEm desc` do banco)
export const inspiracoes: Inspiracao[] = [
  {
    id: 'mercury',
    nome: 'Mercury',
    descricao: 'Contas bancárias para empresas e pessoas',
    url: 'https://mercury.com',
    categorias: ['fintech', 'moderno', 'animado'],
    cores: ['azul', 'branco'],
    imagem: '/mock/mercury.jpg',
    logo: { src: '/mock/logos/mercury.png', iniciais: 'M' },
    bloqueado: true,
  },
  {
    id: 'linear',
    nome: 'Linear',
    descricao: 'Gestão de produto para times e agentes',
    url: 'https://linear.app',
    categorias: ['saas', 'modo-escuro', 'minimalista'],
    cores: ['preto', 'cinza'],
    imagem: '/mock/linear.jpg',
    logo: { src: '/mock/logos/linear.png', iniciais: 'L' },
  },
  {
    id: 'stripe',
    nome: 'Stripe',
    descricao: 'Infraestrutura financeira para a internet',
    url: 'https://stripe.com',
    categorias: ['fintech', 'gradiente', 'animado'],
    cores: ['branco', 'roxo', 'rosa', 'laranja'],
    imagem: '/mock/stripe.jpg',
    logo: { src: '/mock/logos/stripe.png', iniciais: 'S' },
  },
  {
    id: 'vercel',
    nome: 'Vercel',
    descricao: 'Nuvem para construir e publicar na web',
    url: 'https://vercel.com',
    categorias: ['dev-tools', 'pb', 'minimalista'],
    cores: ['preto', 'branco'],
    imagem: '/mock/vercel.jpg',
    logo: { src: '/mock/logos/vercel.png', iniciais: '▲' },
  },
  {
    id: 'cal',
    nome: 'Cal.com',
    descricao: 'Agendamento de reuniões sem troca de e-mails',
    url: 'https://cal.com',
    categorias: ['saas', 'pb', 'minimalista'],
    cores: ['branco', 'preto'],
    imagem: '/mock/cal.jpg',
    logo: { src: '/mock/logos/cal.png', iniciais: 'C' },
  },
  {
    id: 'supabase',
    nome: 'Supabase',
    descricao: 'Postgres com autenticação, storage e APIs',
    url: 'https://supabase.com',
    categorias: ['dev-tools', 'modo-escuro'],
    cores: ['preto', 'verde'],
    imagem: '/mock/supabase.jpg',
    logo: { src: '/mock/logos/supabase.png', iniciais: 'S' },
    bloqueado: true,
  },
  {
    id: 'resend',
    nome: 'Resend',
    descricao: 'E-mail transacional para desenvolvedores',
    url: 'https://resend.com',
    categorias: ['dev-tools', 'pb', 'editorial', 'animado'],
    cores: ['preto', 'branco'],
    imagem: '/mock/resend.jpg',
    logo: { src: '/mock/logos/resend.png', iniciais: 'R' },
  },
  {
    id: 'framer',
    nome: 'Framer',
    descricao: 'Sites do rascunho à publicação, sem código',
    url: 'https://www.framer.com',
    categorias: ['ia', 'modo-escuro', 'moderno', 'animado'],
    cores: ['preto', 'azul'],
    imagem: '/mock/framer.jpg',
    logo: { src: '/mock/logos/framer.png', iniciais: 'F' },
  },
  {
    id: 'ramp',
    nome: 'Ramp',
    descricao: 'Cartões, despesas e pagamentos para empresas',
    url: 'https://ramp.com',
    categorias: ['fintech', 'minimalista', 'moderno'],
    cores: ['branco', 'amarelo', 'preto'],
    imagem: '/mock/ramp.jpg',
    logo: { src: '/mock/logos/ramp.png', iniciais: 'R' },
  },
  {
    id: 'origin',
    nome: 'Origin',
    descricao: 'Consultor financeiro pessoal com IA',
    url: 'https://useorigin.com',
    categorias: ['fintech', 'ia', 'editorial', 'gradiente'],
    cores: ['azul', 'branco'],
    imagem: '/mock/origin.jpg',
    logo: { src: '/mock/logos/origin.png', iniciais: 'O' },
  },
  {
    id: 'cosmos',
    nome: 'Cosmos',
    descricao: 'Um espaço para guardar e organizar inspirações',
    url: 'https://www.cosmos.so',
    categorias: ['pb', 'minimalista'],
    cores: ['branco', 'preto'],
    imagem: '/mock/cosmos.jpg',
    logo: { src: '/mock/logos/cosmos.png', iniciais: 'C' },
  },
  {
    id: 'apple',
    nome: 'Apple',
    descricao: 'iPhone, Mac, iPad, Watch e muito mais',
    url: 'https://www.apple.com',
    categorias: ['minimalista', 'moderno'],
    cores: ['preto', 'branco', 'cinza'],
    imagem: '/mock/apple.jpg',
    logo: { src: '/mock/logos/apple.png', iniciais: 'A' },
  },
  {
    id: 'amplemarket',
    nome: 'Amplemarket',
    descricao: 'Plataforma de vendas com IA para prospecção',
    url: 'https://www.amplemarket.com',
    categorias: ['saas', 'ia', 'gradiente', 'animado'],
    cores: ['branco', 'laranja', 'roxo'],
    imagem: '/mock/amplemarket.jpg',
    logo: { src: '/mock/logos/amplemarket.png', iniciais: 'A' },
  },
  {
    id: 'v7labs',
    nome: 'V7',
    descricao: 'Automação com IA para fluxos cheios de documentos',
    url: 'https://www.v7labs.com',
    categorias: ['ia', 'modo-escuro', 'editorial', 'animado'],
    cores: ['preto', 'cinza', 'laranja'],
    imagem: '/mock/v7labs.jpg',
    logo: { src: '/mock/logos/v7labs.png', iniciais: 'V7' },
  },
  {
    id: 'seed',
    nome: 'Seed',
    descricao: 'Probióticos para a saúde do microbioma',
    url: 'https://seed.com',
    categorias: ['editorial', 'minimalista'],
    cores: ['verde', 'branco'],
    imagem: '/mock/seed.jpg',
    logo: { iniciais: 'S' },
  },
  {
    id: 'superhuman',
    nome: 'Superhuman',
    descricao: 'E-mail, docs e IA em qualquer app',
    url: 'https://superhuman.com',
    categorias: ['saas', 'ia', 'gradiente'],
    cores: ['roxo', 'branco', 'azul'],
    imagem: '/mock/superhuman.jpg',
    logo: { src: '/mock/logos/superhuman.png', iniciais: 'S' },
  },
  {
    id: 'bindplane',
    nome: 'Bindplane',
    descricao: 'Pipeline de telemetria sobre OpenTelemetry',
    url: 'https://bindplane.com',
    categorias: ['dev-tools', 'minimalista', 'moderno'],
    cores: ['branco', 'azul', 'preto'],
    imagem: '/mock/bindplane.jpg',
    logo: { src: '/mock/logos/bindplane.png', iniciais: 'B' },
  },
  {
    id: 'glassflow',
    nome: 'GlassFlow',
    descricao: 'Infraestrutura de dados para agentes de IA',
    url: 'https://www.glassflow.ai',
    categorias: ['dev-tools', 'ia', 'modo-escuro', 'editorial'],
    cores: ['laranja', 'preto'],
    imagem: '/mock/glassflow.jpg',
    logo: { src: '/mock/logos/glassflow.png', iniciais: 'G' },
  },
  {
    id: 'huly',
    nome: 'Huly',
    descricao: 'Plataforma tudo-em-um e open-source para times',
    url: 'https://huly.io',
    categorias: ['saas', 'modo-escuro', 'animado'],
    cores: ['preto', 'branco', 'laranja'],
    imagem: '/mock/huly.jpg',
    logo: { src: '/mock/logos/huly.png', iniciais: 'H' },
  },
  {
    id: 'tuple',
    nome: 'Tuple',
    descricao: 'Pair programming remoto para macOS e Windows',
    url: 'https://tuple.app',
    categorias: ['dev-tools', 'minimalista'],
    cores: ['branco', 'roxo'],
    imagem: '/mock/tuple.jpg',
    logo: { src: '/mock/logos/tuple.png', iniciais: 'T' },
  },
  {
    id: 'dovetail',
    nome: 'Dovetail',
    descricao: 'Inteligência de clientes a partir de feedback',
    url: 'https://dovetail.com',
    categorias: ['saas', 'ia', 'modo-escuro', 'animado'],
    cores: ['preto', 'cinza', 'azul'],
    imagem: '/mock/dovetail.jpg',
    logo: { src: '/mock/logos/dovetail.png', iniciais: 'D' },
  },
  {
    id: 'gitbook',
    nome: 'GitBook',
    descricao: 'Documentação técnica que se mantém atualizada',
    url: 'https://www.gitbook.com',
    categorias: ['dev-tools', 'minimalista', 'moderno'],
    cores: ['branco', 'laranja', 'preto'],
    imagem: '/mock/gitbook.jpg',
    logo: { src: '/mock/logos/gitbook.png', iniciais: 'G' },
  },
  {
    id: 'wope',
    nome: 'Wope',
    descricao: 'Pesquisa de SEO e palavras-chave com IA',
    url: 'https://wope.com',
    categorias: ['saas', 'ia', 'modo-escuro', 'gradiente'],
    cores: ['roxo', 'preto'],
    imagem: '/mock/wope.jpg',
    logo: { src: '/mock/logos/wope.png', iniciais: 'W' },
  },
  {
    id: 'frameio',
    nome: 'Frame.io',
    descricao: 'Revisão e colaboração em vídeo para criativos',
    url: 'https://frame.io',
    categorias: ['saas', 'modo-escuro', 'gradiente'],
    cores: ['roxo', 'preto'],
    imagem: '/mock/frameio.jpg',
    logo: { src: '/mock/logos/frameio.png', iniciais: 'F' },
  },
  {
    id: 'unicorn-studio',
    nome: 'Unicorn Studio',
    descricao: 'Gráficos interativos com shaders para a web',
    url: 'https://www.unicorn.studio',
    categorias: ['saas', 'modo-escuro', 'gradiente', 'animado'],
    cores: ['preto', 'roxo'],
    imagem: '/mock/unicorn-studio.jpg',
    logo: { src: '/mock/logos/unicorn-studio.png', iniciais: 'U' },
  },
  {
    id: 'medusa',
    nome: 'Medusa',
    descricao: 'Plataforma de commerce open-source',
    url: 'https://medusajs.com',
    categorias: ['dev-tools', 'pb', 'minimalista'],
    cores: ['branco', 'preto'],
    imagem: '/mock/medusa.jpg',
    logo: { src: '/mock/logos/medusa.png', iniciais: 'M' },
  },
]
